from datetime import timedelta
from pathlib import Path
import sys
from decouple import Csv,config
from django.core.exceptions import ImproperlyConfigured
BASE_DIR=Path(__file__).resolve().parent.parent
SECRET_KEY=config("SECRET_KEY",default="unsafe-development-key");DEBUG=config("DEBUG",default=False,cast=bool)
if not DEBUG and (SECRET_KEY=="unsafe-development-key" or len(SECRET_KEY)<50):raise ImproperlyConfigured("SECRET_KEY forte é obrigatória em produção.")
ALLOWED_HOSTS=config("ALLOWED_HOSTS",default="localhost,127.0.0.1",cast=Csv())
INSTALLED_APPS=["daphne","django.contrib.admin","django.contrib.auth","django.contrib.contenttypes","django.contrib.sessions","django.contrib.messages","django.contrib.staticfiles","corsheaders","rest_framework","rest_framework_simplejwt.token_blacklist","django_filters","channels","apps.accounts","apps.organizations","apps.subscriptions","apps.work","apps.finance","apps.portal","apps.core"]
MIDDLEWARE=["django.middleware.security.SecurityMiddleware","apps.core.middleware.RequestIdMiddleware","corsheaders.middleware.CorsMiddleware","django.contrib.sessions.middleware.SessionMiddleware","django.middleware.common.CommonMiddleware","django.middleware.csrf.CsrfViewMiddleware","django.contrib.auth.middleware.AuthenticationMiddleware","django.contrib.messages.middleware.MessageMiddleware","django.middleware.clickjacking.XFrameOptionsMiddleware"]
ROOT_URLCONF="config.urls";TEMPLATES=[{"BACKEND":"django.template.backends.django.DjangoTemplates","DIRS":[],"APP_DIRS":True,"OPTIONS":{"context_processors":["django.template.context_processors.request","django.contrib.auth.context_processors.auth","django.contrib.messages.context_processors.messages"]}}];WSGI_APPLICATION="config.wsgi.application";ASGI_APPLICATION="config.asgi.application"
DATABASES={"default":{"ENGINE":"django.db.backends.postgresql","NAME":config("DB_NAME",default="devflow"),"USER":config("DB_USER",default="devflow"),"PASSWORD":config("DB_PASSWORD",default=""),"HOST":config("DB_HOST",default="localhost"),"PORT":config("DB_PORT",default="5432"),"CONN_MAX_AGE":60}}
AUTH_PASSWORD_VALIDATORS=[{"NAME":"django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},{"NAME":"django.contrib.auth.password_validation.MinimumLengthValidator"},{"NAME":"django.contrib.auth.password_validation.CommonPasswordValidator"},{"NAME":"django.contrib.auth.password_validation.NumericPasswordValidator"}]
LANGUAGE_CODE="pt-br";TIME_ZONE="America/Cuiaba";USE_I18N=True;USE_TZ=True
STATIC_URL="/static/";STATIC_ROOT=BASE_DIR/"staticfiles";MEDIA_URL="/media/";MEDIA_ROOT=BASE_DIR/"media";DEFAULT_AUTO_FIELD="django.db.models.BigAutoField";AUTH_USER_MODEL="accounts.User"
FRONTEND_URL=config("FRONTEND_URL",default="http://localhost:5173");CORS_ALLOWED_ORIGINS=[FRONTEND_URL];CSRF_TRUSTED_ORIGINS=config("CSRF_TRUSTED_ORIGINS",default=FRONTEND_URL,cast=Csv())
REST_FRAMEWORK={"DEFAULT_AUTHENTICATION_CLASSES":["rest_framework_simplejwt.authentication.JWTAuthentication"],"DEFAULT_PERMISSION_CLASSES":["rest_framework.permissions.IsAuthenticated"],"DEFAULT_FILTER_BACKENDS":["django_filters.rest_framework.DjangoFilterBackend","rest_framework.filters.SearchFilter","rest_framework.filters.OrderingFilter"],"DEFAULT_PAGINATION_CLASS":"rest_framework.pagination.PageNumberPagination","PAGE_SIZE":20,"EXCEPTION_HANDLER":"apps.core.exceptions.api_exception_handler","DEFAULT_THROTTLE_CLASSES":["rest_framework.throttling.AnonRateThrottle","rest_framework.throttling.UserRateThrottle"],"DEFAULT_THROTTLE_RATES":{"anon":"60/hour","user":"1000/hour","auth":"20/hour","sensitive":"30/hour"}}
SIMPLE_JWT={"ACCESS_TOKEN_LIFETIME":timedelta(minutes=15),"REFRESH_TOKEN_LIFETIME":timedelta(days=7),"ROTATE_REFRESH_TOKENS":True,"BLACKLIST_AFTER_ROTATION":True}
REDIS_URL=config("REDIS_URL",default="redis://redis:6379/0");CACHES={"default":{"BACKEND":"django.core.cache.backends.redis.RedisCache","LOCATION":REDIS_URL}};CHANNEL_LAYERS={"default":{"BACKEND":"channels_redis.core.RedisChannelLayer","CONFIG":{"hosts":[REDIS_URL]}}}
CELERY_BROKER_URL=config("CELERY_BROKER_URL",default=REDIS_URL);CELERY_RESULT_BACKEND=config("CELERY_RESULT_BACKEND",default=REDIS_URL);CELERY_TASK_ALWAYS_EAGER=config("CELERY_TASK_ALWAYS_EAGER",default=DEBUG,cast=bool);CELERY_TASK_TIME_LIMIT=300;CELERY_TASK_SOFT_TIME_LIMIT=240;CELERY_BEAT_SCHEDULE={"invoice-reminders":{"task":"apps.portal.tasks.remind_due_invoices","schedule":86400}}
EMAIL_BACKEND=config("EMAIL_BACKEND",default="django.core.mail.backends.console.EmailBackend");EMAIL_HOST=config("EMAIL_HOST",default="");EMAIL_PORT=config("EMAIL_PORT",default=587,cast=int);EMAIL_HOST_USER=config("EMAIL_HOST_USER",default="");EMAIL_HOST_PASSWORD=config("EMAIL_HOST_PASSWORD",default="");EMAIL_USE_TLS=config("EMAIL_USE_TLS",default=True,cast=bool);DEFAULT_FROM_EMAIL=config("DEFAULT_FROM_EMAIL",default="DevFlow <suporte@localhost>")
PAYMENT_PROVIDER=config("PAYMENT_PROVIDER",default="");PAYMENT_API_KEY=config("PAYMENT_API_KEY",default="");PAYMENT_WEBHOOK_SECRET=config("PAYMENT_WEBHOOK_SECRET",default="");STRIPE_PRO_PRICE_ID=config("STRIPE_PRO_PRICE_ID",default="");PAYMENT_CONTACT=config("PAYMENT_CONTACT",default="")
SECURE_SSL_REDIRECT=not DEBUG;SESSION_COOKIE_SECURE=not DEBUG;CSRF_COOKIE_SECURE=not DEBUG;SECURE_HSTS_SECONDS=31536000 if not DEBUG else 0;SECURE_HSTS_INCLUDE_SUBDOMAINS=not DEBUG;SECURE_HSTS_PRELOAD=not DEBUG;SECURE_PROXY_SSL_HEADER=("HTTP_X_FORWARDED_PROTO","https");SECURE_CONTENT_TYPE_NOSNIFF=True;X_FRAME_OPTIONS="DENY";SECURE_REFERRER_POLICY="strict-origin-when-cross-origin"
LOGGING={"version":1,"disable_existing_loggers":False,"formatters":{"standard":{"format":"{asctime} {levelname} {name} {message}","style":"{"}},"handlers":{"console":{"class":"logging.StreamHandler","formatter":"standard"}},"root":{"handlers":["console"],"level":config("LOG_LEVEL",default="INFO")}}
if "test" in sys.argv:
    CACHES={"default":{"BACKEND":"django.core.cache.backends.locmem.LocMemCache","LOCATION":"devflow-tests"}}
    CHANNEL_LAYERS={"default":{"BACKEND":"channels.layers.InMemoryChannelLayer"}}
    REST_FRAMEWORK["DEFAULT_THROTTLE_RATES"]={"anon":"10000/hour","user":"10000/hour","auth":"10000/hour","sensitive":"10000/hour"}
