# Generated by Django 5.2.16 on 2026-08-24 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_invoice_auto_generate_payment_and_more'),
        ('work', '0002_task_taskattachment_taskcomment_tasklabel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='work.project'),
        ),
    ]
