# Generated by Django 5.2.16 on 2026-08-24 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(default='pt-BR', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='theme',
            field=models.CharField(default='system', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='timezone',
            field=models.CharField(default='America/Cuiaba', max_length=64),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to='avatars/%Y/%m/'),
        ),
    ]
